### ISSUE TITLE
The catalog is not shown in app list

### ISSUE THREAD

**Issue by PPCM** [basschipper/rancher-homeassistant-catalog#5] opened 2020-08-30 23:44 UTC
Hi,

The helm repository is a great idea

Butn I add the  `https://github.com/basschipper/rancher-homeassistant-catalog` in the catalog list. I tryed Helm v2 and v3 version. Like in the attachment.

![téléchargement (1)](https://user-images.githubusercontent.com/1247223/91671939-2d0a6b00-eb2b-11ea-8685-cb1c747708e5.png)

But, there is no homeassistant in the catalog, when I try to launch it.

The Rancher version is 2.4.6 and it is played 3 RPi 4

Any idea?

**Comment by basschipper** [comment] 2020-09-07 09:59
Duplicate of https://github.com/basschipper/rancher-homeassistant-catalog/issues/4

**Closed as completed by basschipper** 2020-09-07 09:59 UTC
